### ISSUE TITLE
I was wondering does this still work in 2017? or do youo suggest another solution?

### ISSUE THREAD

**Issue by seansan** [apeschar/google-shopping-challenge#2]

**Comment by apeschar** [comment]
It never did work-- it's a coding challenge for the purpose of selecting candidates for a vacancy in my company (Kibo IT). See: https://kiboit.com/developers

In any case, this code won't be much help for what you're trying to do, I'm sure.

If you want to compare prices with competitor's shops, try our client's product: https://pricemotion.nl

We can provide assistance or custom development in this regard. If this would be of use, please contact me on albert@kiboit.com
